### ISSUE TITLE
期待更新呀

### ISSUE THREAD

**Issue by samondlee** [animalize/infopi#4]
期待更新呀

**Comment by animalize** [comment]
更新什么啊？程序好像已经很成熟了。

**Comment by samondlee** [comment]
> 更新什么啊？程序好像已经很成熟了。

emmm默认根据兴趣 直接点点鼠标 选择信息源就好了

**Comment by animalize** [comment]
那样代码量会大到不可思议。不如这样，简单，但几乎能处理所有情况。

**Comment by samondlee** [comment]
> 那样代码量会大到不可思议。不如这样，简单，但几乎能处理所有情况。

2333好的
